#!/bin/bash
conf_dir="config"
repos_dir="repos"
for conf_file in $conf_dir/*; do
  name=`basename $conf_file`
  echo "Configure '$name'"
  config=`cat $conf_file`

  repo_dir="$repos_dir/$name"
  mkdir -p $repo_dir
  pushd $repo_dir >/dev/null

  remotes=`echo $config | underscore extract remotes | underscore --outfmt text keys`
  
  if [ ! -d ".git" ]; then
    git init
  fi

  remotes=`echo $config | underscore extract remotes | underscore --outfmt text keys`

  for remote in $remotes; do 
    url=`echo $config | underscore --outfmt text extract remotes.$remote.url`
    echo "Configure remote '$remote' ($url)"
 
    #  git remote rm $remote
    git config --remove-section remote.$remote 2> /dev/null
    git remote add $remote $url
    git config --add remote.$remote.fetch "+refs/tags/*:refs/tags/$remote/*"
    git config remote.$remote.tagopt --no-tags
  done;

  git fetch --all --prune
  popd >/dev/null
done
